[package]
name = "askit-std-agents"
version = "0.1.0"
edition = "2024"
description = "Standard Agents of Agent Stream Kit"
authors = ["Akira Ishino <akira@lumilab.jp>"]
license = "Apache-2.0 OR MIT"

[dependencies]
agent-stream-kit = "0.1"
async-trait = "0.1"
serde_json = "1"
